version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq01
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_USER: delivery_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: food_delivery
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
